spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/nabd
    username: postgres
    password: omar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  application:
    name: alert-service
  kafka:
    consumer:
      group-id: alert-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.nabd.kafka.event

server:
  port: 8084

